### ISSUE TITLE
[Suggestion] Visual feedback

### ISSUE THREAD

**Issue by carallo** [leonixyz/two-finger-history-jump#2]
Hi!

I really like this addon, it works perfectly for me. The only thing it's missing to me is a visual feedback such as a MacOS like animation or the Chrome browser arrow. I think it would greatly help to understand wether the gesture has been received or not. To me the MacOS animation is perfect. Also the Epiphany (GNOME Web) browser has implemented this in a very fluid and nice way.

There was an addon that has now been removed by Mozilla, which I luckily installed when it was available, that has animation implemented, even though it's a bit laggy. It's called [TouchpadSwipe](https://github.com/koseduhemak/touchpadswipe), maybe you can use some of its code.

**Comment by leonixyz** [comment]
Hi,

thanks for the suggestion! I like it. I will release this new feature in the next version soon.

I implemented a prototype, but I don't like 100% how it ended up.

I added a small grey bar fixed to the bottom part of any page which scrolls left/right and when reaches the right/left border triggers the page load.

The bar is only 5px height (configurable) and stretches the whole browser width (it looks similar to a scrollbar), but I'd rather prefer not to modify any part of the page unless the swipe is performed.

I have to check if I can show the bar only during the swipe, and hide it otherwise.

Thanks for using this extension, it started as a personal tool but I see now that >300 people are using it, which is quite a satisfaction.

**Comment by carallo** [comment]
Well thanks to you for taking into account my suggestion!
I like the idea of the bar, it might be a nice way of having a visual feedback. I would say it would be better if the bar appears only during the swipe gesture, but it will be good anyways.

Thank you again!

**Comment by leonixyz** [comment]
This feature has been published with the latest release and should have been pushed to everyone, provided you have automatic updates turned on.

Thank again for the feedback.

**Comment by carallo** [comment]
Thank you! I really like the new bar, the addon is perfect for me now!
I have a problem with nightly, I'll open a new issue for that, but for the rest you really made the use of firefox for me much more pleasant.
Dankeschön!
